### ISSUE TITLE
Gem Load Error is: uninitialized constant RbNaCl::AEAD

### ISSUE THREAD

**Issue by marcelodiegues** [mguymon/paseto.rb#9]
When I start my app server, this error come up. What should I do?

**Comment by AnIrishDuck** [comment]
Is your libsodium version at least `1.0.12`? What version of `rbnacl` are you using?

**Comment by marcelodiegues** [comment]
I had to change the libsodium's path, I don't remember now. I figured out how to resolve my issue with openssl
